# Generated by Django 4.2.17 on 2025-01-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0002_prescription_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_mob_no', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedShelfMapper',
            fields=[
                ('shelfno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medname', models.CharField(max_length=100)),
                ('avail_quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('payment_date_time', models.DateTimeField(auto_now_add=True)),
                ('refund_status', models.CharField(choices=[('Not Initiated', 'Not Initiated'), ('Refunded', 'Refunded')], default='Not Initiated', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.medshelfmapper')),
            ],
        ),
        migrations.CreateModel(
            name='ScannedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image', models.ImageField(upload_to='scanned_prescriptions/')),
                ('extracted_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('Addition', 'Addition'), ('Deduction', 'Deduction')], default='Deduction', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('movement_date_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('shelfno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.medshelfmapper')),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='transaction_date_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescription_details',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='mobno',
            field=models.CharField(default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='medicines_dispensed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='patient_mob_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.patient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.AddField(
            model_name='scannedprescription',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.patient'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.prescription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.transaction'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(related_name='prescriptions', through='medicliq_database.PrescriptionMedicine', to='medicliq_database.medshelfmapper'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='scanned_prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.scannedprescription'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicliq_database.doctor'),
        ),
    ]
