# Generated by Django 4.2.17 on 2025-01-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0003_doctor_medshelfmapper_payment_prescriptionmedicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
    ]
