# Generated by Django 4.2.17 on 2025-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0004_remove_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remarks',
        ),
        migrations.AddField(
            model_name='payment',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
    ]
