# Generated by Django 5.1.3 on 2025-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0008_medshelfmapper_strip_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medshelfmapper',
            name='price_per_unit',
            field=models.FloatField(),
        ),
    ]
