# Generated by Django 5.1.7 on 2025-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0009_alter_medshelfmapper_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tentrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('medastock', models.IntegerField(default=0)),
                ('medbstock', models.IntegerField(default=0)),
                ('medcstock', models.IntegerField(default=0)),
                ('meddstock', models.IntegerField(default=0)),
                ('medestock', models.IntegerField(default=0)),
                ('medfstock', models.IntegerField(default=0)),
                ('medgstock', models.IntegerField(default=0)),
                ('medhstock', models.IntegerField(default=0)),
            ],
        ),
    ]
