# Generated by Django 5.1.7 on 2025-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0010_tentrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentrans',
            name='srno',
            field=models.IntegerField(default=0),
        ),
    ]
