# Generated by Django 5.1.7 on 2025-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicliq_database', '0011_tentrans_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentrans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tentrans',
            name='payment_id',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
